name: List FTP Directory
on: push

jobs:
  list-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: List FTP Root
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Connecting to FTP..."
          lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; ls -la; echo '---'; cd public_html || echo 'no public_html'; ls -la; echo '---'; cd ../domains/marsysexports.in/public_html || echo 'no addon'; ls -la;"
