name: List FTP Directory
on: push

jobs:
  list-ftp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: List FTP Root
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "test1" > test1.txt
          echo "test2" > test2.txt
          lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; put test1.txt -o public_html/test1.txt; put test2.txt -o domains/marsysexports.in/public_html/test2.txt"
          rm -f test1.txt test2.txt

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ftp-log.txt
          git commit -m "Add ftp log"
          git push
